### ISSUE TITLE
Convert [ ] to [[ ]]

### ISSUE THREAD

**Issue by troyengel** [rackerlabs/recap#102]
While reviewing PR #100 I noticed in about 3 places there are old style test operators [ ] use which need to get upgraded to builtin [[ ]] for modern bash4 best practices. Very low priority, since we're using parameter expansion in variables we require bash4 already.

**Comment by tonyskapunk** [comment]
Yes, this is lingering from previous iterations, has to be addressed.

**Comment by tonyskapunk** [comment]
fixed now in `development`
