### ISSUE TITLE
Make use of newer tools for networking stats

### ISSUE THREAD

**Issue by tonyskapunk** [rackerlabs/recap#107]
Most of the network stats depend on old `net-tools`, while this provides compatibility it would be desired to use more modern alternatives.

**Comment by Vascom** [comment]
I agree. net-tools is deprecated an should be replaced by iproute for example.

**Comment by tonyskapunk** [comment]
Hi @Vascom thanks for the interest, this is in the plan, hopefully can be implemented shortly after the release of [1.1.0](https://github.com/rackerlabs/recap/milestone/2)

**Comment by tonyskapunk** [comment]
This was brought to my attention(thanks @carlwgeorge )  this needs to be tackled quickly https://bugzilla.redhat.com/show_bug.cgi?id=1496151

**Comment by troyengel** [comment]
👍

**Comment by tonyskapunk** [comment]
Closing as change has been merged into `development` getting it ready for [1.2.0](https://github.com/rackerlabs/recap/milestone/3)
