### ISSUE TITLE
redhat 6.9 df  unrecognized option

### ISSUE THREAD

**Issue by whogoesoverthere** [rackerlabs/recap#152]
Hello there, 

I have rhel6.9 running  recap-1.3.0-1.el6.noarch and  when I have enabled the MIN_FREE_SPACE check 
I am getting: 

df: unrecognized option '--output=avail'

Seems to be coming from:

    FREE_SPACE=$( df -BM --output=avail "${BASEDIR}" | tail -1 )

Thank you

**Comment by man-chung** [comment]
The "--output" feature was introduced in 2012, as per the [change logs](https://github.com/adtools/coreutils/blob/f94b6dd850452b3260397caee6f983ef59f25df1/ChangeLog#L11991)

`
2012-11-08  Bernhard Voelker  <mail@bernhard-voelker.de>

	df: add --output to select which fields to display
`

According to [Red Hat](https://access.redhat.com/articles/3078) RHEL 6 was  released on on 10 November 2010

So unless Red Hat receives a specific request to update the base code, they will only backport security vulnerabilities/fixes (unless said fix was large enough to warrant pulling in more code)

Obviously, for RHEL 7 was released on 2014, so the base code for "df" would have included the 2012 features.

We probably need a fix to detect which RHEL version, or which df --version is present, and run the awk or cut based code vs the --output feature

**Comment by tonyskapunk** [comment]
@whogoesoverthere thanks for opening this issue, as @man-chung pointed it out the problem is with that change introduced with an argument that is not supported on el6 (el7, deb8+, u14+ support this).

I'll fix that out since el6 won't be EOL until 2020.

**Comment by man-chung** [comment]
Based on the coreutils change logs, it looks like the next release AFTER the --output feature was introduced was v8.21 on 2013-02-14 

So if we want to continue using --output, we can test for the df version

`df --version | head -1 | awk '{print $NF}'`

But thats more code to maintain than just doing the old fashion awk or sed method for all OSes...

**Comment by tonyskapunk** [comment]
> But thats more code to maintain than just doing the old fashion awk or sed method for all OSes...

Indeed, until we stop supporting el6 we will have to use one solution for all, I've done so on PR #153 which should take care of it, I tested on most of the distros recap has been tested so far.

Thanks!

**Comment by tonyskapunk** [comment]
Closing this one, it will be merged into master on the next release.
