### ISSUE TITLE
New kernel updates in RHEL/CentOS 7.5 break iotop output in recap

### ISSUE THREAD

**Issue by THE-Alan-Hicks** [rackerlabs/recap#161]
Kernel updates in RHEL 7.5 have introduced a regression into recap. Red Hat is aware of the issue and is tracking it online here:

  https://access.redhat.com/solutions/3467211

This isn't an issue with recap persay, but rather one with iotop. Still, it would be nice for recap to check for error conditions when running external tools to gather information and handling any errors it detects gracefully.

**Comment by tonyskapunk** [comment]
Thanks for opening this one @THE-Alan-Hicks we definitely could do better with those cases to avoid other reports to get stuck because things like this.

**Comment by tonyskapunk** [comment]
Quickest change just to avoid the problem seeing with `iotop` @THE-Alan-Hicks could you please confirm this works?  I tested locally and seems to be working.

**Comment by tonyskapunk** [comment]
Merged into `development` I expect to release 1.4.0 pretty soon.
