### ISSUE TITLE
Package recap as .rpm and .deb files

### ISSUE THREAD

**Issue by gusmaskowitz** [rackerlabs/recap#18]
Please package recap as .rpm and .deb files for simpler install and management on the server side. It is a great tool, but it is not acceptable to clone live code down from github on production machines. 

I'm happy to help with the SPEC files and package creation, but wanted to log this issue so that it is visible and we can discuss and collaborate.

**Comment by cgtx** [comment]
RPMs are now available at https://copr.fedoraproject.org/coprs/cgtx/recap/.
