### ISSUE TITLE
MySQL InnoDB status relies on pid_file option providing the full path

### ISSUE THREAD

**Issue by tonodor** [rackerlabs/recap#220]
I just discovered that the InnoDB report does not work if the pid_file option does not provide a full path.
For example, with MySQL 5.5 onto EL7, if the pid-file option is missing in my.cnf the service will set the value to the server hostname by default and the file is created inside the datadir:

[root@server-02 ~]# mysql -Bse "SHOW VARIABLES LIKE 'datadir'; SHOW VARIABLES LIKE 'pid_file';"
datadir /var/lib/mysql/
pid_file        server-02.pid
[root@server-02 ~]# ls -al /var/lib/mysql/server-02.pid
-rw-rw----. 1 mysql mysql 5 May 22 16:26 /var/lib/mysql/server-02.pid

There should be a check to confirm that the option is providing a full path and prefix the datadir if not.

**Comment by tonyskapunk** [comment]
Hi @tonodor thanks for taking the time in reporting this, I'll take a look to this to get it addressed.

If you feel like would like to contribute, you can find more info in https://github.com/rackerlabs/recap/blob/master/CONTRIBUTING.md PRs are welcome :smiley:

**Comment by tonodor** [comment]
Hey @tonyskapunk 
I've just created #222 to fix this issue 👍

**Comment by tonyskapunk** [comment]
Thanks so much @tonodor I'll review this one tomorrow morning

**Comment by tonyskapunk** [comment]
@tonodor thank you for the report and also for providing the fix!!
