### ISSUE TITLE
reorganize repo

### ISSUE THREAD

**Issue by cgtx** [rackerlabs/recap#23]
I'll take input from anyone, but specifically I'm looking for @bhgraham, @siso, and @buzzboy23 opinions.  What do you think about organizing the files into directories?  I created a branch "organize" where you can see the direction I am thinking about.  Specifically, move core files into src, and supplementary stuff into util.

**Comment by siso** [comment]
Hey @cgtx, I like as it is neater.

Will it still be possibile to install *recap* from sources (```./recap-installer.sh```)?
Or when creating RPM we could use ```Makefile``` to change current dir layout to this one.

**Comment by cgtx** [comment]
Either way.  Obviously the source paths in recap-installer.sh and the rpm spec would need to be adjusted.  Creating a Makefile might be the "proper" way to go, but I'm not very good with Makefile syntax.

**Comment by siso** [comment]
I'm happy with writing the Makefile, and create, say, a ./rpm directory where building RPM package happens.
Do we have a script or document to create the RPM?

**Comment by cgtx** [comment]
I can handle the RPM part.  Set up the makefile to follow this pattern.

```
./configure --prefix=/usr
make DESTDIR=%{buildroot} install
```

If not specified, the `--prefix` should be `/usr/local/` so that way manual installs go there.

**Comment by cgtx** [comment]
RPMs are now available at https://copr.fedoraproject.org/coprs/cgtx/recap/.

**Comment by cgtx** [comment]
Also, a good makefile would probably make recap-installer.sh obsolete, right?

**Comment by siso** [comment]
Well spotted! ;)
Indeed, let's have different targets in Makefile to create RPM and install recap: ```make rpm``` and ```make install```

**Comment by bhgraham** [comment]
As I do not use recap solely on Redhat, I would prefer any redhat or
distribution specific files to go in their own directories.  Anything core
to recap should be in the top level directory.

If you are going to go the Makefile path, then at least build it from the
start for Debian and Redhat both.  I could help with the debian piece
(preferably using checkinstall).

Really the makefile should be able to install on any *NIX distribution.


Benjamin H. Graham
http://bman.io

On Wed, Jan 7, 2015 at 4:30 PM, Simone Soldateschi <notifications@github.com

**Comment by siso** [comment]
@bhgraham I think files should be in the dirs below:

```
bin
etc
man
```

Then ```rpm``` and ```dist``` dirs would be created by ```make rpm```, and deleted by ```make clean```.

**Comment by carlgeorge** [comment]
Don't bother trying to create an RPM via the Makefile (`make rpm`).  Just have the Makefile do the basics of putting the files in place.  The RPM spec file will handle calling `make install` and then creating the RPM.

**Comment by siso** [comment]
@carlgeorge sounds good to me
I do not like all files in just one dir either.

How would you create the RPM package?

**Comment by carlgeorge** [comment]
The RPM is created by [the spec file](https://github.com/rackerlabs/recap/blob/master/recap.spec).

**Comment by man-chung** [comment]
Since I merged some PRs, I made a new branch for reorganising:

https://github.com/rackerlabs/recap/tree/reorg

MAn

**Comment by man-chung** [comment]
Delete "organize" since we are now working on "reorg" (reorg contains latest merges where as organize does not).

**Comment by thebwt** [comment]
So can we make reorg master? The debian package is built directly form that branch, the install script is adjusted for those paths, and the RPM should be able to adjust (I believe in them). Can we call the reorg done and work forward from there?

**Comment by carlwgeorge** [comment]
The reorg branch has been merged into master with an appropriate Makefile.
