### ISSUE TITLE
Add my account to allow write into this repository

### ISSUE THREAD

**Issue by tonyskapunk** [rackerlabs/recap#232]
I'm not with Rackspace any longer and thus my account has been removed from the `rackerlabs` org.

I remain maintaining this repository and some of their packages. But I need to be added as an [outside collaborator](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization) with writing permissions to allow me triage issues (add/edit/remove comments/tags), review code and merge code as well.

Thanks!

**Comment by terackspace** [comment]
@tonyskapunk I've attempted to add you directly to the repo as an Outside Code-Destroyer, there should be an invite waiting for you...

**Comment by tonyskapunk** [comment]
@terackspace thanks for the quick response, I've accepted the invitation and I see I have the expected permissions as before :smile_cat: 

Thanks again!!
