### ISSUE TITLE
Document MAXLOAD option

### ISSUE THREAD

**Issue by mstevens** [rackerlabs/recap#27]
Tried to run recap on a moderately loaded server, only to get a MAXLOAD related error.

Was able to get it to run by reading the source and setting the MAXLOAD option, but this is not documented.

Please add to the docs :)

**Comment by carlgeorge** [comment]
How are you running recap?  If you are running the code from the master branch (or from the copr I set up) then MAXLOAD is going to [default to 0.8](https://github.com/rackerlabs/recap/blob/c427a878aa34b6de2cb90748404d14b74bab0310/recap#L52).  In the development version, this has been improved to instead default to the number of cores of the server (see #25).  I also have #26 open to better describe this in the comments of the script.

**Comment by mstevens** [comment]
I'm running the master branch, where it seems to default to 0.8 and is totally undocumented.

**Comment by man-chung** [comment]
MAXLOAD=1000 now, and has been merged into master. 
Closing.
