### ISSUE TITLE
Recap does not use custom my.cnf files for mysql process list

### ISSUE THREAD

**Issue by timoguic** [rackerlabs/recap#36]
The script does not use the custom my.cnf files that are specified in /etc/recap. More precisely, line 328 and 335:

----
                                mysql -e "show full processlist\G" >> $MYSQL_FILE
----
                        mysqladmin -v processlist >> $MYSQL_FILE
----

The above throws an error if MySQL root requires a password... I guess the whole block should be enclosed in a 'for cnf in $DOTMYDOTCNF' and use --defaults-extra-file=$cnf, or something similar.

Problem encountered on a RackSpace cloud server running Ubuntu 14.04 LTS.

**Comment by tonyskapunk** [comment]
Hi @timoguic, seems like what you reported was fixed back in 07eb9b93, thanks.
