### ISSUE TITLE
Dependencies List

### ISSUE THREAD

**Issue by man-chung** [rackerlabs/recap#40]
bc
/root/.my.cnf

**Comment by carlwgeorge** [comment]
`/root/.my.cnf` isn't needed if the mysql report is disabled, correct?  The latest versions of RPM have the idea of "weak" dependencies, where a package can suggest other packages, but not strictly require them.  Unfortunately, it will be a while before RHEL gets that capability.  I think the dependency list in the README should differentiate between the items that are 100% required, and those that are optional based on the configured reports.  That information will be useful for the spec file.  I went ahead and added `bc` as a dependency in the spec file (and `net-tools` for the netstat command), but not anything mysql-related, as that will be a much more involved dependency load.  Let me know if you would like the recap RPM to strictly require anything else.

**Comment by man-chung** [comment]
Sweet, sounds good to me. Thanks!
