### ISSUE TITLE
Feature request: top swap consumers

### ISSUE THREAD

**Issue by kimvette** [rackerlabs/recap#43]
When we get paging tickets there is often only a very brief window where we can capture what is hitting swap - yesterday I sat on an open ticket on a server that was flapping, because I missed the paging event then I finally caught it in action. It would be great if this script could be included in recap/rs-sysmon (you'll recognize this one from one of the Linux one-liners page - not mine):

 ` # echo -e "\n== Top 10 Processes By Swap Usage: =="; ( printf "%s\t%s\t%s\n" "PID" "PROCESS" "SWAP"; (for i in /proc/[0-9]*; do PID=${i#/proc/}; NAME=$(awk '/Name/ {print $2}' ${i}/status 2>/dev/null); SWAP=$(awk '/Swap/ { sum+=$2 }; END { print sprintf("%.2f", sum/1024) "M" }' /${i}/smaps 2>/dev/null);echo ${PID} ${NAME} ${SWAP}; done | awk '!/0.00M/' |sort -grk3,3 | head -10)) | column -t;`

It would be even better if runbook automation could capture this in ticket updates in response to alerts - but I suppose that would be an IAW thing?

**Comment by eljrax** [comment]
Hi @kimvette 

The amount of swap used is not necessarily directly in correlation to the amount of pressure a process exerts on the swap. 
Long-lived, rarely used pages are often put into swap, even when there are free residential pages available! They're also not automatically read back in if there at some point in time has been an issue with memory resources and the situation improves to the point where pages in swap could fit into residential memory again. That only happens on-access. 
 
So it's usually not the amount of swap used that's of interest, but rather what frequently reads and writes the pages to swap. This oneliner doesn't exactly address that, and as you say, perhaps best placed in runbook.
It might point you in the right direction however, so it's still a useful thing to have in your tool-belt!

My 2p!
