### ISSUE TITLE
recap log.gz files don't rotate

### ISSUE THREAD

**Issue by Nohau** [rackerlabs/recap#61]
I have noticed the recap gzip files don't rotate properly after looking into it the regex is wrong inside /usr/sbin/recaplog here is a example : 

find $BASEDIR -maxdepth 1 -regextype grep -regex "${BASEDIR}/[a-z]*_[0-9]{8}-[0-9]{6}.log.gz" -type f -mtime +$LOG_EXPIRY -exec echo rm {} \;  | tee -a $LOGFILE

The file name is the following that gets made when rotated : 

netstat_daily_20160602.log.gz

So as you can see there is no - and actually another _  . If we where rotating just the log file this would have worked but this is not the case : 

ps_20160607-012001.log

As you see it has the single _ and a single - between the dates .  

I created a temporary work around on my side by replacing the find regex

FROM:

-regex "${BASEDIR}/[a-z]*_[0-9]{8}-[0-9]{6}.log.gz" 

TO:

-regex "${BASEDIR}/[a-z]__[a-z]__[0-9]*.log.gz"

Now it actually finds the gzip files and it can rotate them out as per the configuration.

**Comment by thebwt** [comment]
That's a pretty simple fix, why don't you open a pull request (make sure to mention "issue #61"), and then you can get the credit for the change.

**Comment by tonyskapunk** [comment]
This should be addressed by #72

**Comment by tonyskapunk** [comment]
Fixed in #72
