### ISSUE TITLE
Execution via Cron is enabled by default

### ISSUE THREAD

**Issue by kruzda** [rackerlabs/recap#74]
The readme clearly states that: "By default the cron execution of the program is not enabled."
Yet in the file https://github.com/rackerlabs/recap/blob/master/src/recap.cron which is copied to /etc/cron.d during installation, the following line is not commented:
*/10 * * * * root /usr/sbin/recap

**Comment by tonyskapunk** [comment]
@kruzda thanks for pointing that out, I've committed #75  to clarify that indeed the cronjob is enabled and not only for `recap` but also for `recaplog`.
