### ISSUE TITLE
recap.conf enables FULLSTATUS by default causing email spam (bad config)

### ISSUE THREAD

**Issue by troyengel** [rackerlabs/recap#94]
The recap.conf configuration has this enabled/on by default:
https://github.com/rackerlabs/recap/blob/master/src/recap.conf#L54
```
# Use "service httpd fullstatus"
# Please ensure that the Apache is configured to allow access to the
# http://localhost/server-status URL before enabling this option
USEFULLSTATUS=yes
```

The internal default for this variable is no:
https://github.com/rackerlabs/recap/blob/master/src/recap#L66
```
USEFULLSTATUS="no"
```

This is broken in a few ways:

1. The code uses 'apachectl fullstatus' not 'service httpd fullstatus' as documented
1. The default external config does not mirror the internal defaults; all out of the box configs should mirror the application's default behaviour, not alter it
1. By enabling this, the system keeps running the command when Apache is not installed and/or running and emailing root@localhost by default every single time it runs

The config file should mirror the internal default and be set to =no to work correctly out of the box on a server that does not have Apache installed or does not have it running. As is, it's spamming my root@localhost with the error output every 10 minutes (default cron) when it runs. Thanks!

**Comment by tonyskapunk** [comment]
It will be sane to look at all default settings as well, as I believe the one you reported would  not be the only one, thanks for the report.

**Comment by tonyskapunk** [comment]
Documenting here the current defaults:

### `recap.conf` or `/etc/recap`
```bash
$ sed -e 's/^#.*//' -e '/^$/d' src/recap.conf 
MAILTO=
LOG_COMPRESS=1
LOG_EXPIRY=15
EMAIL_ON_ERROR=1
EMAIL_ON_ERROR_RECIPIENTS="root@localhost"
EMAIL_ON_ERROR_SUBJECT="recaplog error"
USEPS=yes
USERESOURCES=yes
USESAR=no
USESARR=no
USESARQ=no
USEFULLSTATUS=yes
USEPSTREE=no
USENETSTAT=yes
USENETSTATSUM=no
USEMYSQL=yes
USEMYSQLPROCESSLIST=yes
USEINNODB=no
DOTMYDOTCNF=/root/.my.cnf
MYSQL_PROCESS_LIST=table
USEDF=yes
USESLAB=no
USEFDISK=no
BACKUP_ITEMS="fdisk mysql netstat ps pstree resources"
MIN_FREE_SPACE=0
OPTS_DF="-x nfs"
OPTS_FDISK="-l"
OPTS_FREE=""
OPTS_IOSTAT="-t -x 1 3"
OPTS_IOTOP="-b -o -t -n 3"
OPTS_NETSTAT="-ntulpae"
OPTS_NETSTAT_SUM="-s"
OPTS_PS="auxfww"
OPTS_PSTREE=""
OPTS_VMSTAT="-S M 1 3"
```

### `recap`
```bash
$ sed -n '/bin\/bash/,/# BEGIN/p' src/recap | sed -e 's/^#.*//' -e '/^$/d'
LOG_SUFFIX=$(date +%Y%m%d-%H%M%S)
PATH=/bin:/usr/bin:/sbin:/usr/sbin
BASEDIR="/var/log/recap"
DATE=`date +%Y-%m-%d_%H:%M:%S`
ROTATELOGS="yes"
SNAPSHOT="no"
BACKUP="no"
LOCKFILE="/var/lock/recap.lock"
BACKUP_ITEMS="fdisk mysql netstat ps pstree resources"
MAXLOAD="1000"
OPTS_DF="-x nfs"
OPTS_FDISK="-l"
OPTS_FREE=""
OPTS_IOSTAT="-t -x 1 3"
OPTS_IOTOP="-b -o -t -n 3"
OPTS_NETSTAT="-ntulpae"
OPTS_NETSTAT_SUM="-s"
OPTS_PS="auxfww"
OPTS_PSTREE=""
OPTS_VMSTAT="-S M 1 3"
USEPS="yes"
USERESOURCES="yes"
USESAR="no"
USESARR="no"
USESARQ="no"
USEFULLSTATUS="no"
ROTATE="7"
USEPSTREE="no"
USENETSTAT="no"
USENETSTATSUM="no"
USEMYSQL="no"
USEMYSQLPROCESSLIST="no"
USEDF="no"
USESLAB="no"
USEINNODB="no"
DOTMYDOTCNF="/root/.my.cnf"
USEFDISK="no"
MYSQL_PROCESS_LIST="table"
MIN_FREE_SPACE=0
OUTPUTDIR_MODE="750"
```

### recaplog
```bash
$ sed -n '/bin\/bash/,/^## FUNCTIONS/p' src/recaplog | sed -e 's/^#.*//' -e '/^$/d'
PATH=/bin:/usr/bin:/sbin:/usr/sbin
BASEDIR="/var/log/recap"
LOCKFILE="/var/lock/recaplog.lock"
LOG_COMPRESS=1
LOG_EXPIRY=0
BACKUP_ITEMS="fdisk mysql netstat ps pstree resources"
LOGFILE="${BASEDIR}/recaplog.log"
EMAIL_ON_ERROR=1
EMAIL_ON_ERROR_SUBJECT="recaplog error"
EMAIL_ON_ERROR_RECIPIENTS="root@localhost"
```

### recaptool
```bash
$ sed -n '/bin\/bash/,/^cmds/p' src/recaptool | sed -e 's/^#.*//' -e '/^$/d'
ME=`basename $0`
RECAPPATH="/var/log/recap"
cmds=""
```

**Comment by troyengel** [comment]
The USEMYSQL* options look like a target we should think about as well, it's default =no but the config is =yes. I think it should follow the Apache change, as not everyone will have MySQL installed by default. I would love for the SAR to be enabled by default, but that's also not installed by default by vendors. :-/

**Comment by tonyskapunk** [comment]
Right, there are quite a few defaults settings that need to be changed. I'm documenting them all and will provide the details pretty soon.

**Comment by StafDehat** [comment]
I'd suggest making sar/sysstat a dependency of the recap package.  Apache and MySQL, yeah that'll vary, but if people want recap logs, it stands to reason that they're not opposed to having sar.

**Comment by tonyskapunk** [comment]
It is already [a dependency](https://github.com/rackerlabs/recap/blob/master/util/packaging/rpm/recap.spec#L11), not only for sar(script), but sysstat(package) provides other scripts that are consumed by recap.

**Comment by carlwgeorge** [comment]
Speaking of, can I get a list of packages that enhance recap, such as httpd and mysql/mariadb?  There is a newer RPM concept called [weak](http://rpm.org/user_doc/dependencies.html#weak-dependencies) [dependencies](https://fedoraproject.org/wiki/Packaging:WeakDependencies) that let you specify optional dependencies.  It's only applicable to Fedora (RPM 4.12+), but I can conditionalize it in the spec file to not cause errors on EL.

**Comment by tonyskapunk** [comment]
Sure, shouldn't be a problem, I'm building a "map" to track the dependencies on the settings available, I should be able to provide that list, although I'll provide for both RPMs and DEBs.

**Comment by tonyskapunk** [comment]
I've documented all the current status of the defaults, personal [notes are here](https://gist.github.com/tonyskapunk/ce601c67014982a8509f410bc661c974), I'm working on aligning them and will come up with a PR once completed.

**Comment by troyengel** [comment]
it's a lot of work - if you want to make Issues for groups of work, I am happy to help tackle some of it. :) I left a small comment on the gist...

**Comment by tonyskapunk** [comment]
Just a quick update in here(due my lack of updates), I'm working on this, taking me good amount of time due to all the documentation and moving pieces of every single setting across the code, config and documentation(man pages)

**Comment by tonyskapunk** [comment]
Ton of changes, on PR #100 

A resume of the changes is:

- EMAIL_ON_ERROR, EMAIL_ON_ERROR_SUBJECT, EMAIL_ON_ERROR_RECIPIENTS - removed(not used)
- MAXLOAD - 10*cpu(dynamic by default, was 1000)
- LOG_EXPIRY - default 15(by default was 0, but set to 15 in the recap conf)
- ROTATE, ROTATELOGS - removed(not used)
- USEDF - default is now enabled(by default was disabled, but enabled in the recap conf)
- USEFULLSTATUS - Functionality reimplemented to avoid being tied to a web browser.
- USEMYSQL - disabled(by default was disabled, but enabled in the recap conf)
- USEMYSQLPROCESSLIST - disabled(by default was disabled, but enabled in the recap conf)
- USENETSTAT - default is enabled(by default was disabled, but enabled in the recap conf)
- USESAR - default is enabled(by default was disabled)
- OPTS_PSTREE - default is "-p"(by default was empty '')
- OPTS_STATUSURL - default is "http://localhost:80/"(this is a new option used by USEFULLSTATUS)
- Snapshots file name now matches regular logs and backups.

---

A test performed to validate the changes:

OLD:
```bash
# now=$(date +%Y%m%d-%H%M%S); date; recap; recap --backup; recap --snapshot
Fri Jul  7 17:06:32 UTC 2017
Connection refused
Connection refused

# ls -ltr /var/log/recap/*${now}*
-rw-r--r--. 1 root root 8508 Jul  7 17:06 /var/log/recap/ps_20170707-170632.log
-rw-r--r--. 1 root root 5060 Jul  7 17:06 /var/log/recap/resources_20170707-170632.log
-rw-r--r--. 1 root root 2185 Jul  7 17:06 /var/log/recap/netstat_20170707-170632.log
-rw-r--r--. 1 root root  684 Jul  7 17:06 /var/log/recap/mysql_20170707-170632.lo


# ls -ltr /var/log/recap/backups/
total 36
-rw-r--r--. 1 root root  297 Jul  7 17:06 fdisk_20170707-163738.log
-rw-r--r--. 1 root root  684 Jul  7 17:06 mysql_20170707-170632.log
-rw-r--r--. 1 root root 2185 Jul  7 17:06 netstat_20170707-170632.log
-rw-r--r--. 1 root root 8508 Jul  7 17:06 ps_20170707-170632.log
-rw-r--r--. 1 root root  841 Jul  7 17:06 pstree_20170707-163738.log
-rw-r--r--. 1 root root 5060 Jul  7 17:06 resources_20170707-170632.log


## Note that the above copied the last logs available based of BACKUP_ITEMS, hence the difference on timestamps.

# ls -ltr /var/log/recap/snapshots/
total 28
-rw-r--r--. 1 root root 8519 Jul  7 17:06 ps.log_snapshot_2017-07-07_17:06:42
-rw-r--r--. 1 root root 4975 Jul  7 17:06 resources.log_snapshot_2017-07-07_17:06:42
-rw-r--r--. 1 root root 2185 Jul  7 17:06 netstat.log_snapshot_2017-07-07_17:06:42
-rw-r--r--. 1 root root  684 Jul  7 17:06 mysql.log_snapshot_2017-07-07_17:06


# \rm /var/log/recap/{backups,snapshots}/*
```

NEW:
```bash
# now=$(date +%Y%m%d-%H%M%S); date; recap; recap --backup; recap --snapshot
Fri Jul  7 17:11:15 UTC 2017

# ls -ltr /var/log/recap/*${now}*
-rw-r--r--. 1 root root 8872 Jul  7 17:11 /var/log/recap/ps_20170707-171115.log
-rw-r--r--. 1 root root 5593 Jul  7 17:11 /var/log/recap/resources_20170707-171115.log
-rw-r--r--. 1 root root 2308 Jul  7 17:11 /var/log/recap/netstat_20170707-171115.log


## Note above mysql is not being generated by default anymore after this change.

# ls -ltr /var/log/recap/backups
total 36
-rw-r--r--. 1 root root  297 Jul  7 17:11 fdisk_20170707-163738.log
-rw-r--r--. 1 root root  684 Jul  7 17:11 mysql_20170707-171001.log
-rw-r--r--. 1 root root 2308 Jul  7 17:11 netstat_20170707-171115.log
-rw-r--r--. 1 root root 8872 Jul  7 17:11 ps_20170707-171115.log
-rw-r--r--. 1 root root  841 Jul  7 17:11 pstree_20170707-163738.log
-rw-r--r--. 1 root root 5593 Jul  7 17:11 resources_20170707-171115.log

## Note above copied the last logs available based of BACKUP_ITEMS, hence the difference on timestamps.

# ls -ltr /var/log/recap/snapshots
total 24
-rw-r--r--. 1 root root 8883 Jul  7 17:11 ps_20170707-171126.log_snapshot
-rw-r--r--. 1 root root 5296 Jul  7 17:11 resources_20170707-171126.log_snapshot
-rw-r--r--. 1 root root 2308 Jul  7 17:11 netstat_20170707-171126.log_snapshot

## Note above the filename are now standard accross locations.
```

**Comment by troyengel** [comment]
I have not had a chance to run it yet, but reading the changes 👍 it all looks great. I noticed that in the src/recap we set defaults with quotes (FOO="no") but in recap.conf we do not use quotes (FOO=no). OCD comment. :-)

**Comment by tonyskapunk** [comment]
Ah!, forgot to note in here that I've included the observations from @troyengel in the PR already.

**Comment by tonyskapunk** [comment]
PR #100 has been merged into `development`, this can be closed now, current self-imposed target is to release this early Aug into `master`.
