### ISSUE TITLE
Move daily files in to subfolder

### ISSUE THREAD

**Issue by kevi5702** [rackerlabs/recap#97]
Wanted to suggest a feature enhancement that log.gz files be placed in a subfolder such as:
/var/log/recap/daily

This may make it a bit easier to parse/organize log files under recap that has been running for some time. Happy to make the PR if this seems like a good enhancement to others.

**Comment by tonyskapunk** [comment]
Hey @kevi5702 , on `1.0.0` some of this is already implemented, [documented in the code here](https://github.com/rackerlabs/recap/blob/master/src/recaplog#L144-L149), this was introduced in  #72, the way a similar behavior occurs is through `recaplog`, `recap` keeps populating logs into `/var/log/recap`,  `recaplog` is the one that takes care of moving logs on a daily basis and performs two different options through the setting `LOG_COMPRESSION`. What's important to notice is that it's a **requirement** to have `recaplog` running daily to move those, `recap` is not responsible for moving them around.

Then to have the functionality you are looking for you can have: `LOG_COMPRESSION=0` anyway the `LOG_COMPRESSION=1` is also going to put them into a directory but is going to compress them and let them in `/var/log/recap`, hence when extracting will end up in its own directory.

Going to close this one, but feel free to re-open if you think it's needed.
